# More information at this link: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
updates:
  - package-ecosystem: pnpm
    commit-message:
      prefix: pnpm
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
version: 2
