import "./Currency";
import "./Date";
import "./DateTime";
import "./Duration";
import "./EmailAddress";
import "./HexColorCode";
import "./IP";
import "./IPv4";
import "./IPv6";
import "./JSONObject";
import "./Latitude";
import "./Longitude";
import "./NegativeFloat";
import "./NegativeInt";
import "./NonEmptyString";
import "./NonNegativeFloat";
import "./NonNegativeInt";
import "./NonPositiveFloat";
import "./NonPositiveInt";
import "./PhoneNumber";
import "./PositiveFloat";
import "./PositiveInt";
import "./Time";
import "./TimeZone";
import "./Timestamp";
import "./URL";
import "./UTCOffset";

import type { Currency } from "./Currency";
import type { _Date } from "./Date";
import type { DateTime } from "./DateTime";
import type { Duration } from "./Duration";
import type { EmailAddress } from "./EmailAddress";
import type { HexColorCode } from "./HexColorCode";
import type { IP } from "./IP";
import type { IPv4 } from "./IPv4";
import type { Ipv6 } from "./IPv6";
import type { JSONObject } from "./JSONObject";
import type { Latitude } from "./Latitude";
import type { Longitude } from "./Longitude";
import type { NegativeFloat } from "./NegativeFloat";
import type { NegativeInt } from "./NegativeInt";
import type { NonEmptyString } from "./NonEmptyString";
import type { NonNegativeFloat } from "./NonNegativeFloat";
import type { NonNegativeInt } from "./NonNegativeInt";
import type { NonPositiveFloat } from "./NonPositiveFloat";
import type { NonPositiveInt } from "./NonPositiveInt";
import type { PhoneNumber } from "./PhoneNumber";
import type { PositiveFloat } from "./PositiveFloat";
import type { PositiveInt } from "./PositiveInt";
import type { Time } from "./Time";
import type { TimeZone } from "./TimeZone";
import type { Timestamp } from "./Timestamp";
import type { _URL } from "./URL";
import type { UTCOffset } from "./UTCOffset";

/**
 * Map of custom scalar types used in talawa api used to annotate the type of those scalars to the pothos schema builder intiializer for type-safe usage of those scalars in the pothos schema definitions.
 */
export type CustomScalars = {
	Currency: Currency;
	Date: _Date;
	DateTime: DateTime;
	Duration: Duration;
	EmailAddress: EmailAddress;
	HexColorCode: HexColorCode;
	IP: IP;
	IPv4: IPv4;
	IPv6: Ipv6;
	JSONObject: JSONObject;
	Latitude: Latitude;
	Longitude: Longitude;
	NegativeFloat: NegativeFloat;
	NegativeInt: NegativeInt;
	NonEmptyString: NonEmptyString;
	NonNegativeFloat: NonNegativeFloat;
	NonNegativeInt: NonNegativeInt;
	NonPositiveFloat: NonPositiveFloat;
	NonPositiveInt: NonPositiveInt;
	PhoneNumber: PhoneNumber;
	PositiveFloat: PositiveFloat;
	PositiveInt: PositiveInt;
	Time: Time;
	TimeZone: TimeZone;
	Timestamp: Timestamp;
	URL: _URL;
	UTCOffset: UTCOffset;
};

/**
 * Map of custom scalar types used in talawa api used to annotate the type of those scalars to the clients consuming talawa api for type-safe usage of those scalars in the graphql operation documents.
 */
export type ClientCustomScalars = {
	CountryCode: string;
	Currency: string;
	Date: string;
	DateTime: string;
	Duration: string;
	EmailAddress: string;
	HexColorCode: string;
	IP: string;
	IPv4: string;
	IPv6: string;
	JSONObject: Record<string, unknown>;
	Latitude: number;
	Longitude: number;
	NegativeFloat: number;
	NegativeInt: number;
	NonEmptyString: string;
	NonNegativeFloat: number;
	NonNegativeInt: number;
	NonPositiveFloat: number;
	NonPositiveInt: number;
	PhoneNumber: string;
	PositiveFloat: number;
	PositiveInt: number;
	Time: string;
	TimeZone: string;
	Timestamp: number;
	URL: string;
	UTCOffset: string;
};
