// import "./Advertisement/index";
// import "./AgendaItem/index";
// import "./AgendaSection/index";
import "./AuthenticationPayload";
// import "./Comment/index";
// import "./Event/index";
// import "./Family/index";
// import "./Fund/index";
// import "./FundraisingCampaign/index";
import "./Mutation/index";
import "./Organization/index";
// import "./Pledge/index";
// import "./Post/index";
import "./Query/index";
import "./Subscription/index";
// import "./Tag/index";
import "./User/index";
// import "./Venue/index";
